### ISSUE TITLE
Error at npm start

### ISSUE THREAD

**Issue by silverHub** [frnkst/retro-tech-quiz#52]
Steps:
- clone
- npm i
- npm start

_**Note: Yarn works**_

Last step result in error:
```
node version: v14.16.0
npm version: 6.14.11

> retro-tech-quiz@0.1.0 start C:\TH\Work\retro-tech-quiz
> craco start

(node:13804) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tailwindcss'
Require stack:
- C:\TH\Work\retro-tech-quiz\craco.config.js
- C:\TH\Work\retro-tech-quiz\node_modules\@craco\craco\lib\config.js
- C:\TH\Work\retro-tech-quiz\node_modules\@craco\craco\scripts\start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\TH\Work\retro-tech-quiz\craco.config.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In 
the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by frnkst** [comment]
I've updated the readme with a getting started section. You think we should also make it work with npm? I don't really want to support both because I would always need to update two lock files when adding new dependencies.

**Comment by frnkst** [comment]
Added package-lock.json to .gitignore
